In [1]:
import pandas as pd

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
ans_hard = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Mini Project Advance Python/Insurance/Insurance/answer_hard.csv')

In [4]:
ans_hard.head()

id  Gender  Age  Driving_License  Region_Code  Previously_Insured  \
0  380110    Male   30                1         28.0                   1   
1  380111    Male   45                1          8.0                   1   
2  380112  Female   20                1         37.0                   0   
3  380113  Female   22                1         28.0                   0   
4  380114  Female   32                1         30.0                   1   

  Vehicle_Age Vehicle_Damage  Annual_Premium  Policy_Sales_Channel  Vintage  \
0    < 1 Year             No         50094.0                 152.0       38   
1    1-2 Year             No         44110.0                  26.0      110   
2    < 1 Year            Yes         47019.0                 160.0      104   
3    < 1 Year            Yes          2630.0                 160.0       42   
4    < 1 Year             No         31210.0                 152.0      136   

   Response  DecisionTree  RandomForest  VotingClassifierHard  
0         0             0             0                     0  
1         0             0             0                     0  
2         0             1             1                     1  
3         1             1             1                     1  
4         0             0             0                     0

In [5]:
len(ans_hard[ans_hard['DecisionTree'] != ans_hard['RandomForest']])

0

In [6]:
ans_soft = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Mini Project Advance Python/Insurance/Insurance/answer_soft.csv')

In [7]:
ans_soft.head()

id  Gender  Age  Driving_License  Region_Code  Previously_Insured  \
0  380110    Male   30                1         28.0                   1   
1  380111    Male   45                1          8.0                   1   
2  380112  Female   20                1         37.0                   0   
3  380113  Female   22                1         28.0                   0   
4  380114  Female   32                1         30.0                   1   

  Vehicle_Age Vehicle_Damage  Annual_Premium  Policy_Sales_Channel  Vintage  \
0    < 1 Year             No         50094.0                 152.0       38   
1    1-2 Year             No         44110.0                  26.0      110   
2    < 1 Year            Yes         47019.0                 160.0      104   
3    < 1 Year            Yes          2630.0                 160.0       42   
4    < 1 Year             No         31210.0                 152.0      136   

   Response  DecisionTree  RandomForest  VotingClassifierSoft  
0         0             0             0                     0  
1         0             0             0                     0  
2         0             1             1                     1  
3         1             1             1                     1  
4         0             0             0                     0

In [8]:
len(ans_soft[ans_soft['DecisionTree'] != ans_soft['RandomForest']])

0

In [9]:
(ans_hard['VotingClassifierHard'] != ans_soft['VotingClassifierSoft']).sum()

0

In [10]:
differences = ans_hard['VotingClassifierHard'].compare(ans_soft['VotingClassifierSoft'])
len(differences)

0

In [24]:
import joblib

loaded_model_hard = joblib.load('/content/drive/MyDrive/Colab Notebooks/Mini Project Advance Python/Insurance/Insurance/voting_clf_hard_model.pkl')
loaded_model_soft = joblib.load('/content/drive/MyDrive/Colab Notebooks/Mini Project Advance Python/Insurance/Insurance/voting_clf_soft_model.pkl')

In [11]:
top_3_features = ['Previously_Insured', 'Policy_Sales_Channel', 'Vehicle_Age_> 2 Years']

In [12]:
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Mini Project Advance Python/Insurance/Insurance/insurance_data.csv')

In [22]:
import numpy as np

feature_list = []
for feature in top_3_features:
  if feature in df.columns:
    unique_list = df[feature].unique().tolist()
    feature_list.append(unique_list)
    print(unique_list)
  else:
    unique_list = [0, 1]
    feature_list.append(unique_list)
    print(unique_list)
  print()

[0, 1]

[26.0, 152.0, 160.0, 124.0, 14.0, 13.0, 30.0, 156.0, 163.0, 157.0, 122.0, 19.0, 22.0, 15.0, 154.0, 16.0, 52.0, 155.0, 11.0, 151.0, 125.0, 25.0, 61.0, 1.0, 86.0, 31.0, 150.0, 23.0, 60.0, 21.0, 121.0, 3.0, 139.0, 12.0, 29.0, 55.0, 7.0, 47.0, 127.0, 153.0, 78.0, 158.0, 89.0, 32.0, 8.0, 10.0, 120.0, 65.0, 4.0, 42.0, 83.0, 136.0, 24.0, 18.0, 56.0, 48.0, 106.0, 54.0, 93.0, 116.0, 91.0, 45.0, 9.0, 145.0, 147.0, 44.0, 109.0, 37.0, 140.0, 107.0, 128.0, 131.0, 114.0, 118.0, 159.0, 119.0, 105.0, 135.0, 62.0, 138.0, 129.0, 88.0, 92.0, 111.0, 113.0, 73.0, 36.0, 28.0, 35.0, 59.0, 53.0, 148.0, 133.0, 108.0, 64.0, 39.0, 94.0, 132.0, 46.0, 81.0, 103.0, 90.0, 51.0, 27.0, 146.0, 63.0, 96.0, 40.0, 66.0, 100.0, 95.0, 123.0, 98.0, 75.0, 69.0, 130.0, 134.0, 49.0, 97.0, 38.0, 17.0, 110.0, 80.0, 71.0, 117.0, 58.0, 20.0, 76.0, 104.0, 87.0, 84.0, 137.0, 126.0, 68.0, 67.0, 101.0, 115.0, 57.0, 82.0, 79.0, 112.0, 99.0, 70.0, 2.0, 34.0, 33.0, 74.0, 102.0, 149.0, 43.0, 6.0, 50.0, 144.0, 143.0, 41.0]

[0, 1]



In [49]:
feature1 = feature_list[0]
feature2 = feature_list[1]
feature3 = feature_list[2]

result_list_hard = []
result_list_soft = []
result_list_soft_proba = []
feature_combine = []

for i in feature1:
  for j in feature2:
    for k in feature3:
      input_data = pd.DataFrame([[i, j, k]], columns=top_3_features)
      feature_combine.append([i, j, k])

      predictions_hard = {}
      for idx, model in enumerate(loaded_model_hard.estimators_):
        predictions_hard[f'model_{idx}'] = model.predict(input_data)
      result_list_hard.append(predictions_hard)

      predictions_soft = {}
      for idx, model in enumerate(loaded_model_soft.estimators_):
        predictions_soft[f'model_{idx}'] = model.predict(input_data)
      result_list_soft.append(predictions_soft)

      predictions_soft_proba = {}
      for idx, model in enumerate(loaded_model_soft.estimators_):
        predictions_soft_proba[f'model_{idx}'] = model.predict_proba(input_data)
      result_list_soft_proba.append(predictions_soft_proba)

# Hard Voting

In [60]:
for i in range(len(result_list_hard)):
  result_hard = list(result_list_hard[i].values())

  if result_hard[0] != result_hard[1]:
    print('\nHard Voting')
    print(f'Features: {feature_combine[i]}')
    print(f'Predict: {result_hard}')


Hard Voting
Features: [0, 126.0, 0]
Predict: [array([0]), array([1])]

Hard Voting
Features: [1, 144.0, 1]
Predict: [array([1]), array([0])]

Hard Voting
Features: [1, 143.0, 1]
Predict: [array([1]), array([0])]


In [61]:
X = np.array([
    [0, 126.0, 0],
    [1, 144.0, 1],
    [1, 143.0, 1]
])

input_data = pd.DataFrame(X, columns=top_3_features)

y_pred = loaded_model_hard.predict(input_data)
y_pred.reshape(-1,1)

array([[0],
       [0],
       [0]])

# Soft Voting

In [66]:
for i in range(len(result_list_soft)):
  result_soft = list(result_list_soft[i].values())

  if result_soft[0] != result_soft[1]:
    print('\nSoft Voting')
    print(f'Features: {feature_combine[i]}')
    print(f'Predict: {result_soft}')
    print(f'Probability: {result_list_soft_proba[i]}')


Soft Voting
Features: [0, 126.0, 0]
Predict: [array([0]), array([1])]
Probability: {'model_0': array([[0.5, 0.5]]), 'model_1': array([[0.30979252, 0.69020748]])}

Soft Voting
Features: [1, 145.0, 1]
Predict: [array([1]), array([0])]
Probability: {'model_0': array([[0., 1.]]), 'model_1': array([[0.52, 0.48]])}

Soft Voting
Features: [1, 146.0, 1]
Predict: [array([1]), array([0])]
Probability: {'model_0': array([[0., 1.]]), 'model_1': array([[0.51846473, 0.48153527]])}

Soft Voting
Features: [1, 144.0, 1]
Predict: [array([1]), array([0])]
Probability: {'model_0': array([[0., 1.]]), 'model_1': array([[0.52, 0.48]])}

Soft Voting
Features: [1, 143.0, 1]
Predict: [array([1]), array([0])]
Probability: {'model_0': array([[0., 1.]]), 'model_1': array([[0.52, 0.48]])}


In [67]:
X = np.array([
    [0, 126.0, 0],
    [1, 145.0, 1],
    [1, 146.0, 1],
    [1, 144.0, 1],
    [1, 143.0, 1]
])

input_data = pd.DataFrame(X, columns=top_3_features)

y_pred = loaded_model_soft.predict(input_data)
y_pred.reshape(-1,1)

array([[1],
       [1],
       [1],
       [1],
       [1]])

In [68]:
y_pred = loaded_model_soft.predict_proba(input_data)
y_pred

array([[0.40489626, 0.59510374],
       [0.26      , 0.74      ],
       [0.25923237, 0.74076763],
       [0.26      , 0.74      ],
       [0.26      , 0.74      ]])